// NoteNameMappings.ts
import {
  octaveZeroNoteNames,
  octaveOneNoteNames,
  octaveTwoNoteNames,
  octaveThreeNoteNames,
} from "../models/NoteName";

// 1. Define the parallel English-note arrays:
const englishOctaveZero = [
  "G", "Ab--", "Ab-",
  "Ab", 
  "A-b", "A-", 
  "A", "Bb-",
  "Bb", "Bb+", "Bb++", 
  "B-b", "B--", "B-", 
  "B", "B+",
  "C", 
  "C-#",
  "C#", "C#+",
  "D", "Eb--", "Eb-",
  "Eb", "Eb+",
  "E-b", "E-",
  "E", "E+",
  "F", "F+",
  "F-#", "F#-",
  "F#", "F#+","G-",
];

const englishOctaveOne = [
  "G", "Ab--", "Ab-",
  "Ab", 
  "A-b", "A-", 
  "A", "Bb-",
  "Bb", "Bb+", "Bb++", 
  "B-b", "B--", "B-", 
  "B", "B+",
  "C", 
  "C-#",
  "C#", "C#+",
  "D", "Eb--", "Eb-",
  "Eb", "Eb+",
  "E-b", "E-",
  "E", "E+",
  "F", "F+",
  "F-#", "F#-",
  "F#", "F#+","G-",
];

const englishOctaveTwo = [
  "g", "ab--", "ab-",
  "ab",
  "a-b", "a-",
  "a", "bb-",
  "bb", "bb+", "bb++",
  "b-b", "b--", "b-",
  "b", "b+",
  "c",
  "c-#",
  "c#", "c#+",
  "d", "eb--", "eb-",
  "eb", "eb+",
  "e-b", "e-",
  "e", "e+",
  "f", "f+",
  "f-#", "f#-",
  "f#", "f#+", "g-",
];

const englishOctaveThree = [
  "g", "ab--", "ab-",
  "ab",
  "a-b", "a-",
  "a", "bb-",
  "bb", "bb+", "bb++",
  "b-b", "b--", "b-",
  "b", "b+",
  "c",
  "c-#",
  "c#", "c#+",
  "d", "eb--", "eb-",
  "eb", "eb+",
  "e-b", "e-",
  "e", "e+",
  "f", "f+",
  "f-#", "f#-",
  "f#", "f#+", "g-",
];

// 2. A small helper to zip Arabic→English:
function makeMap(arabic: string[], english: string[]) {
  if (arabic.length !== english.length) {
    throw new Error("octave arrays and english arrays must be same length");
  }
  return Object.fromEntries(arabic.map((a, i) => [a, english[i]]));
}

// 3. Build the single mapping by merging all four octaves:
export const arabicToEnglishNoteMapping = {
  ...makeMap(octaveZeroNoteNames,  englishOctaveZero),
  ...makeMap(octaveOneNoteNames,   englishOctaveOne),
  ...makeMap(octaveTwoNoteNames,   englishOctaveTwo),
  ...makeMap(octaveThreeNoteNames, englishOctaveThree),
};

function splitEnglishNoteName(englishNoteName: string) {
    return { englishNoteNameNatural: englishNoteName[0], englishNoteNameAccidental: englishNoteName.slice(1) }
}

export function getEnglishNoteName(arabicName: string): string{
  const mapping = arabicToEnglishNoteMapping[arabicName]
  if (mapping) return splitEnglishNoteName(mapping).englishNoteNameNatural + splitEnglishNoteName(mapping).englishNoteNameAccidental
  else return "--";
}

/* 
export const arabicToEnglishNoteMapping: Record<string, string> = {
  "qarār yegāh": "G",
  "qarār qarār nīm ḥiṣār": "Ab-",
  "qarār shūrī": "Ab",
  "qarār qarār ḥiṣār": "Ab+",
  "qarār qarār tīk ḥiṣār/shūrī": "A-",
  "qarār nīm ʿushayrān": "A",
  "qarār ʿushayrān": "Bb-",
  "qarār nīm ʿajam ʿushayrān": "Bb",
  "qarār ʿajam ʿushayrān": "Bb+",
  "qarār nairūz": "B-b",
  "qarār tīk ʿajam ʿushayrān": "B-",
  "qarār ʿirāq": "B-",
  "qarār rahāwī": "B",
  "qarār nīm kawasht/rahāwī": "B+",
  "qarār kawasht": "C",
  "qarār tīk kawasht": "C+",
  "qarār rāst": "C-#",
  "qarār nīm zirguleh": "C#",
  "qarār zirguleh": "C#+",
  "qarār tīk zirguleh": "D",
  "qarār dūgāh": "D+",
  "qarār nīm kurdī/nahāwand": "Eb",
  "qarār nahāwand": "Eb+",
  "qarār kurdī": "E-b",
  "qarār tīk kūrdī": "E-",
  "qarār segāh": "E",
  "qarār nīm buselīk": "E+",
  "qarār buselīk/ʿushshāq": "F",
  "qarār tīk buselīk": "F+",
  "qarār chahargāh": "F-#",
  "qarār tīk chahargāh": "F#",
  "qarār nīm ḥijāz": "F#+",
  "qarār ṣabā": "g-",
  "qarār ḥijāz": "g",
  "qarār tīk ḥijāz/ṣabā": "ab-",
  "nīm yegāh": "ab",
  yegāh: "G",
  "qarār nīm ḥiṣār": "Ab-",
  "qarār ḥiṣār": "Ab",
  "qarār tīk ḥiṣār/shūrī": "Ab+",
  "nīm ʿushayrān": "A-",
  ʿushayrān: "A",
  "nīm ʿajam ʿushayrān": "Bb-",
  "ʿajam ʿushayrān": "Bb",
  "tīk ʿajam ʿushayrān": "Bb+",
  ʿirāq: "B-b",
  "nīm kawasht": "B-",
  kawasht: "B",
  "tīk kawasht": "B+",
  rāst: "C",
  "tīk rāst": "C+",
  "nīm zirguleh": "C-#",
  zirguleh: "C#",
  "tīk zirguleh": "C#+",
  dūgāh: "D",
  "nīm kurdī/nahāwand": "D+",
  kurdī: "Eb",
  "tīk kūrdī": "Eb+",
  segāh: "E-b",
  "nīm buselīk": "E-",
  "buselīk/ʿushshāq": "E",
  "tīk buselīk": "E+",
  chahargāh: "F",
  "tīk chahargāh": "F+",
  "nīm ḥijāz": "F-#",
  ḥijāz: "F#",
  "tīk ḥijāz/ṣabā": "F#+",
  "nīm nawā": "g-",
  nawā: "g",
  "nīm ḥiṣār": "ab-",
  ḥiṣār: "ab",
  "tīk ḥiṣār": "ab+",
  "nīm ḥuseinī": "a-",
  ḥuseinī: "a",
  "nīm ʿajam": "bb-",
  ʿajam: "bb",
  "tīk ʿajam": "bb+",
  awj: "b-b",
  "nīm māhūr": "b-",
  māhūr: "b",
  "tīk māhūr": "b+",
  kurdān: "c",
  "tīk kurdān": "c+",
  "nīm shahnāz": "c-#",
  shahnāz: "c#",
  "jawāb tīk zirguleh": "c#+",
  muḥayyar: "d",
  "nīm sunbuleh": "d+",
  "sunbuleh/zawāl": "eb",
  "jawāb tīk kūrdī": "eb+",
  buzurk: "e-b",
  "jawāb nīm buselīk": "e-",
  "jawāb buselīk": "e",
  "jawāb tīk buselīk": "e+",
  mahurān: "f",
  "tīk mahurān": "f+",
  "jawāb nīm ḥijāz": "f-#",
  "jawāb ḥijāz": "f#",
  "jawāb tīk ḥijāz": "f#+",
  "nīm saham/ramal tūtī": "g-",
  "saham/ramal tūtī": "g",
  "jawāb nīm ḥiṣār": "ab-",
  "jawāb ḥiṣār": "ab",
  "jawāb tīk ḥiṣār": "ab+",
  "jawāb ḥuseinī": "a",
  "jawāb nīm ʿajam": "bb-",
  "jawāb ʿajam": "bb",
  "jawāb tīk ʿajam": "bb+",
  "jawāb awj": "b-b",
  "jawāb nīm māhūr": "b-",
  "jawāb māhūr": "b",
  "jawāb tīk māhūr": "b+",
  "jawāb kurdān": "c",
}; 

// Returns the English name for a given Arabic note name (or "--" if not found). 
export function getEnglishNoteName(arabicName: string): string {
  return arabicToEnglishNoteMapping[arabicName] || "--";
}
  */

// -----------------------
// Abjad arrays
// -----------------------
export const abjadNames = [
  "آ",
  "ب",
  "ج",
  "د",
  "ه",
  "و",
  "ز",
  "ح",
  "ط",
  "ي",
  "ك",
  "ل",
  "م",
  "ن",
  "س",
  "ع",
  "ف",
  "ص",
  "ق",
  "ر",
  "ش",
  "ت",
  "ث",
  "خ",
  "ذ",
  "ض",
  "ظ",
  "غ",
  "يا",
  "يب",
  "يج",
  "يد",
  "يه",
  "يو",
  "يز",
  "يح",
  "يط",
  "كا",
  "كب",
  "كج",
  "كد",
  "كه",
  "كو",
  "كز",
  "كح",
  "كط",
  "لا",
  "لب",
  "لج",
  "لد",
  "له",
  "لو",
  "لز",
  "لح",
  "لط",
];
