export const octaveZeroNoteNames = [
  "qarār yegāh",
  "qarār qarār nīm ḥiṣār",
  "qarār shūrī",
  "qarār qarār ḥiṣār",
  "qarār qarār tīk ḥiṣār/shūrī",
  "qarār nīm ‘ushayrān",
  "qarār ‘ushayrān",
  "qarār nīm ‘ajam ‘ushayrān",
  "qarār ‘ajam ‘ushayrān",
  "qarār nairūz",
  "qarār tīk ’ajam ’ushayrān",
  "qarār ‘irāq",
  "qarār rahāwī",
  "qarār nīm kawasht/rahāwī",
  "qarār kawasht",
  "qarār tīk kawasht",
  "qarār rāst",
  "qarār nīm zirguleh",
  "qarār zirguleh",
  "qarār tīk zirguleh",
  "qarār dogāh",
  "qarār nīm kurdī/nahāwand",
  "qarār nahāwand",
  "qarār kurdī",
  "qarār tīk kūrdī",
  "qarār segāh",
  "qarār nīm buselīk",
  "qarār buselīk/’ushshāq",
  "qarār tīk buselīk",
  "qarār chahargāh",
  "qarār nīm ḥijāz",
  "qarār ṣabā",
  "qarār ḥijāz",
  "qarār tīk ḥijāz/ṣabā",
];
export const octaveOneNoteNames = [
  "yegāh",
  "qarār nīm ḥiṣār",
  "shūrī",
  "qarār ḥiṣār",
  "qarār tīk ḥiṣār/shūrī",
  "nīm ‘ushayrān",
  "‘ushayrān",
  "nīm ‘ajam ‘ushayrān",
  "‘ajam ‘ushayrān",
  "nairūz",
  "tīk ’ajam ’ushayrān",
  "‘irāq",
  "rahāwī",
  "nīm kawasht",
  "kawasht",
  "tīk kawasht",
  "rāst",
  "nīm zirguleh",
  "zirguleh",
  "tīk zirguleh",
  "dūgāh",
  "nīm kurdī/nahāwand",
  "nahāwand",
  "kurdī",
  "tīk kūrdī",
  "segāh",
  "nīm buselīk",
  "buselīk/’ushshāq",
  "tīk buselīk",
  "chahargāh",
  "nīm ḥijāz",
  "ṣabā",
  "ḥijāz",
  "tīk ḥijāz/ṣabā",
];
export const octaveTwoNoteNames = [
  "nawā",
  "nīm ḥiṣār",
  "jawāb shūrī",
  "ḥiṣār",
  "tīk ḥiṣār",
  "nīm ḥuseinī",
  "ḥuseinī",
  "nīm ‘ajam",
  "‘ajam",
  "jawāb nairūz",
  "tīk ’ajam",
  "’awj",
  "jawāb rahāwī",
  "nīm māhūr",
  "māhūr",
  "tīk māhūr",
  "kurdān",
  "nīm shahnāz",
  "shahnāz",
  "jawāb tīk zirguleh",
  "muḥayyar",
  "nīm sunbuleh",
  "jawāb nahāwand",
  "sunbuleh/zawāl",
  "jawāb tīk kūrdī",
  "buzurk",
  "jawāb nīm buselīk",
  "jawāb buselīk",
  "jawāb tīk buselīk",
  "mahurān",
  "jawāb nīm ḥijāz",
  "jawāb ṣabā",
  "jawāb ḥijāz",
  "jawāb tīk ḥijāz",
];
export const octaveThreeNoteNames = [
  "saham/ramal tūtī",
  "jawāb nīm ḥiṣār",
  "jawāb jawāb shūrī",
  "jawāb ḥiṣār",
  "jawāb tīk ḥiṣār",
  "jawāb nīm ḥuseinī",
  "jawāb ḥuseinī",
  "jawāb nīm ‘ajam",
  "jawāb ‘ajam",
  "jawāb jawāb nairūz",
  "jawāb tīk ’ajam",
  "jawāb ’awj",
  "jawāb jawāb rahāwī",
  "jawāb nīm māhūr",
  "jawāb māhūr",
  "jawāb tīk māhūr",
  "jawāb kurdān",
  "jawāb nīm shahnāz",
  "jawāb shahnāz",
  "jawāb jawāb tīk zirguleh",
  "jawāb muḥayyar",
  "jawāb nīm sunbuleh",
  "jawāb jawāb nahāwand",
  "jawāb sunbuleh/zawāl",
  "jawāb jawāb tīk kūrdī",
  "jawāb buzurk",
  "jawāb jawāb nīm buselīk",
  "jawāb jawāb buselīk",
  "jawāb jawāb tīk buselīk",
  "jawāb mahurān",
  "jawāb jawāb nīm ḥijāz",
  "jawāb jawāb ṣabā",
  "jawāb jawāb ḥijāz",
  "jawāb jawāb tīk ḥijāz",
];

export const octaveFourNoteNames = [
  "jawāb saham/ramal tūtī",
  "jawāb jawāb nīm ḥiṣār",
  "jawāb jawāb jawāb shūrī",
  "jawāb jawāb ḥiṣār",
  "jawāb jawāb tīk ḥiṣār",
  "jawāb jawāb nīm ḥuseinī",
  "jawāb jawāb ḥuseinī",
  "jawāb jawāb nīm ‘ajam",
  "jawāb jawāb ‘ajam",
  "jawāb jawāb jawāb nairūz",
  "jawāb jawāb tīk ’ajam",
  "jawāb jawāb ’awj",
  "jawāb jawāb jawāb rahāwī",
  "jawāb jawāb nīm māhūr",
  "jawāb jawāb māhūr",
  "jawāb jawāb tīk māhūr",
  "jawāb jawāb kurdān",
  "jawāb jawāb nīm shahnāz",
  "jawāb jawāb shahnāz",
  "jawāb jawāb jawāb tīk zirguleh",
  "jawāb jawāb muḥayyar",
  "jawāb jawāb nīm sunbuleh",
  "jawāb jawāb jawāb nahāwand",
  "jawāb jawāb sunbuleh/zawāl",
  "jawāb jawāb jawāb tīk kūrdī",
  "jawāb jawāb buzurk",
  "jawāb jawāb jawāb nīm buselīk",
  "jawāb jawāb jawāb buselīk",
  "jawāb jawāb jawāb tīk buselīk",
  "jawāb jawāb mahurān",
  "jawāb jawāb jawāb nīm ḥijāz",
  "jawāb jawāb jawāb ṣabā",
  "jawāb jawāb jawāb ḥijāz",
  "jawāb jawāb jawāb tīk ḥijāz",
]

export const allNotes = [
  ...new Set([
    ...octaveZeroNoteNames,
    ...octaveOneNoteNames,
    ...octaveTwoNoteNames,
    ...octaveThreeNoteNames,
    ...octaveFourNoteNames,
  ]),
] as const;

type TransliteratedNoteName = typeof allNotes[number];
export default TransliteratedNoteName;
export type TransliteratedNoteNameOctaveOne = typeof octaveOneNoteNames[number];
export type TransliteratedNoteNameOctaveZero = typeof octaveZeroNoteNames[number];
export type TransliteratedNoteNameOctaveTwo = typeof octaveTwoNoteNames[number];
export type TransliteratedNoteNameOctaveThree = typeof octaveThreeNoteNames[number];
export type TransliteratedNoteNameOctaveFour = typeof octaveFourNoteNames[number];