export const OctaveOneNoteNames = [
  "yegāh",
  "qarār nīm ḥiṣār",
  "qarār ḥiṣār",
  "qarār tīk ḥiṣār",
  "nīm 'ushayrān",
  "'ushayrān",
  "nīm 'ajam 'ushayrān",
  "'ajam 'ushayrān",
  "tīk 'ajam 'ushayrān",
  "'irāq",
  "nīm kawasht/rahāwī",
  "kawasht",
  "tīk kawasht",
  "rāst",
  "tīk rāst",
  "nīm zirguleh",
  "zirguleh",
  "tīk zirguleh",
  "dogāh",
  "nīm kurdī/nahāwand",
  "kurdī",
  "tīk kūrdī",
  "segāh",
  "nīm buselīk",
  "buselīk/'ushshāq",
  "tīk buselīk",
  "chahargāh",
  "tīk chahargāh",
  "nīm ḥijāz",
  "ḥijāz",
  "tīk ḥijāz/ṣabā",
  "nīm nawā",
  "nawā",
  "nīm ḥiṣār",
  "ḥiṣār",
  "tīk ḥiṣār",
  "nīm ḥuseinī",
  "ḥuseinī",
  "nīm 'ajam",
  "'ajam",
  "tīk 'ajam",
  "awj",
  "nīm māhūr",
  "māhūr",
  "tīk māhūr",
  "kurdān",
] as const;

export const octaveZeroNotesNames = [
  "qarār yegāh",
  "qarār qarār nīm ḥiṣār",
  "qarār shūrī",
  "qarār qarār ḥiṣār",
  "qarār qarār tīk ḥiṣār",
  "qarār nīm 'ushayrān",
  "qarār 'ushayrān",
  "qarār nīm 'ajam 'ushayrān",
  "qarār 'ajam 'ushayrān",
  "qarār nairūz",
  "qarār tīk 'ajam 'ushayrān",
  "qarār 'irāq",
  "qarār rahāwī",
  "qarār nīm kawasht/rahāwī",
  "qarār kawasht",
  "qarār tīk kawasht",
  "qarār rast",
  "qarār nīm zirguleh",
  "qarār zirguleh",
  "qarār tīk zirguleh",
  "qarār dogāh",
  "qarār nīm kurdī/nahāwand",
  "qarār nahāwand",
  "qarār kurdī",
  "qarār tīk kūrdī",
  "qarār segāh",
  "qarār nīm buselīk",
  "qarār buselīk/'ushshāq",
  "qarār tīk buselīk",
  "qarār chahargāh",
  "qarār nīm ḥijāz",
  "qarār ṣabā",
  "qarār ḥijāz",
  "qarār tīk ḥijāz/ṣabā",
] as const;

export const octaveTwoNoteNames = [
  "nawā",
  "nīm ḥiṣār",
  "jawāb shūrī",
  "ḥiṣār",
  "tīk ḥiṣār",
  "nīm ḥuseinī",
  "ḥuseinī",
  "nīm 'ajam",
  "'ajam",
  "jawāb nairūz",
  "tīk 'ajam",
  "'awj",
  "jawāb rahāwī",
  "nīm māhūr",
  "māhūr",
  "tīk māhūr",
  "kurdān",
  "nīm shahnāz",
  "shahnāz",
  "jawāb tīk zirguleh",
  "muḥayyar",
  "nīm sunbuleh",
  "jawāb nahāwand",
  "sunbuleh/zawāl",
  "jawāb tīk kūrdī",
  "buzurk",
  "jawāb nīm buselīk",
  "jawāb buselīk",
  "jawāb tīk buselīk",
  "mahurān",
  "jawāb nīm ḥijāz",
  "jawāb ṣabā",
  "jawāb ḥijāz",
  "jawāb tīk ḥijāz",
] as const;

export const octaveThreeNoteNames = [
  "saham/ramal tūti",
  "jawāb nīm ḥiṣār",
  "jawāb jawāb shūrī",
  "jawāb ḥiṣār",
  "jawāb tīk ḥiṣār",
  "jawāb nīm ḥuseinī",
  "jawāb ḥuseinī",
  "jawāb nīm 'ajam",
  "jawāb 'ajam",
  "jawāb jawāb nairūz",
  "jawāb tīk 'ajam",
  "jawāb 'awj",
  "jawāb jawāb rahāwī",
  "jawāb nīm māhūr",
  "jawāb māhūr",
  "jawāb tīk māhūr",
  "jawāb kurdān",
  "jawāb nīm shahnāz",
  "jawāb shahnāz",
  "jawāb jawāb tīk zirguleh",
  "jawāb muḥayyar",
  "jawāb nīm sunbuleh",
  "jawāb jawāb nahāwand",
  "jawāb sunbuleh/zawāl",
  "jawāb jawāb tīk kūrdī",
  "jawāb buzurk",
  "jawāb jawāb nīm buselīk",
  "jawāb jawāb buselīk",
  "jawāb jawāb tīk buselīk",
  "jawāb mahurān",
  "jawāb jawāb nīm ḥijāz",
  "jawāb jawāb ṣabā",
  "jawāb jawāb ḥijāz",
  "jawāb jawāb tīk ḥijāz",
] as const;

export const allNotes = [
  ...new Set([
    ...OctaveOneNoteNames,
    ...octaveZeroNotesNames,
    ...octaveTwoNoteNames,
    ...octaveThreeNoteNames,
  ]),
] as const;

type NoteName = typeof allNotes[number];

export default NoteName;